[package]
name = "rsfb"
version = "0.1.0"
authors = ["Aleksey Verkholat <elseecay@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"

[build-dependencies]
cmake = "*"
bindgen = "*"

